### ISSUE TITLE
Cannot send the message_payload TLV according to the SMPP protocol

### ISSUE THREAD

**Issue by atheeqrc** [ukarim/smppgui#6]
According to SMPP protocol, short_message is used to send messages which is less than 255 characters and message_payload TLV is used to send messages more than 255 characters.

It has also mentioned that either short_message or message_payload should be set. But the empty check for short_message doesnt allow to send message_payload. 

Please refer the pdf for the protocol specification. 

[Short_message and Message_payload TLV issue.pdf](https://github.com/ukarim/smppgui/files/14138379/Short_message.and.Message_payload.TLV.issue.pdf)

**Comment by atheeqrc** [comment]
Raised a PR for this issue. PR : #7

**Comment by ukarim** [comment]
pr has been merged
